fix ota partitions override
COMPATIBLE

2026-08-17 22:59:28 - check_target_files_vintf.py - INFO    : stderr:
2026-08-17 22:59:28 - ota_from_target_files.py - WARNING : Builds
doesn't support zucchini, or source/target don't have compatible
zucchini versions. Disabling zucchini.
2026-08-17 22:59:28 - ota_from_target_files.py - WARNING : Source build
doesn't support lz4diff, or source/target don't have compatible lz4diff
versions. Disabling lz4diff.
2026-08-17 22:59:28 - ota_utils.py - INFO    : target files
/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju
is already extracted
2026-08-17 22:59:28 - common.py - INFO    :   Running:
"/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/delta_generator
--out_file
/home/ashallowperson/android_development/project-infinity-x/out/soong/.t
emp/payload-kw242f78.bin --partition_names
dpm:gz:lk:logo:mcupm:md1img:odm:pi_img:scp:spmfw:sspm:system_dlkm:tee:tkv
--new_partitions
/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/d
pm.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/gz.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/lk.img:/home/ashal
lowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/logo.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/mcupm.img:/home/ashallowperson/and
roid_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/md1img.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/IMAGES/odm.img:/home/ashallowperson/android_develop
ment/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/pi_img.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/scp.img:/home/ashallowperson/android_development/project-
infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/spmfw.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/sspm.img:/home/ashallowperson/android_development/project-infinity-x/ou
t/soong/.temp/target_filespc1v_wju/IMAGES/system_dlkm.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/tee.img:/home/ashallowperson/android_development/project-infinity-x/out/soong
/.temp/target_filespc1v_wju/RADIO/tkv.img --new_mapfiles
::::::/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/IMAGES/odm.map:::::/home/ashallowperson/android_development/project-infinity-x
/out/soong/.temp/target_filespc1v_wju/IMAGES/system_dlkm.map::
--new_postinstall_config_file
/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/META/postinstall_config.txt
--dynamic_partition_
info_file
/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/META/dynamic_partitions_info.txt
--apex_info_file
/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/targe
t_filespc1v_wju/META/apex_info.pb --major_version 2
--security_patch_level 2026-07-01 --enable_zucchini=false
--enable_lz4diff=false --enable_vabc_xor=true --max_timestamp 1786987767
--partition_timestamps odm:1786987767,system_dlkm:17869
87767"
[0817/225928.451460:ERROR:payload_generation_config.cc(152)] No valid
postinstall config found.
[0817/225928.451494:FATAL:generate_delta_main.cc(691)] Check failed:
payload_config.target.LoadPostInstallConfig(store).
/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/../lib64/libchrome.so(base::debug::StackTrace::StackTrace(unsigned
long)+0x1b) [0x7df7e4f02f2b]
/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/../lib64/libchrome.so(logging::LogMessage::~LogMessage()+0x8c)
[0x7df7e4e9220c]
/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/delta_generator(+0x110a25)
[0x5e6f0283ca25]
/usr/lib/x86_64-linux-gnu/libc.so.6(+0x2a601) [0x7df7e482a601]
/usr/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x88)
[0x7df7e482a718]
/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/delta_generator(+0x10e529)
[0x5e6f0283a529]

2026-08-17 22:59:28 - common.py - INFO    :
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
File
"/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/ota_from_target_files/__main__.py",
line 52, in <module>
File
"/home/ashallowperson/android_development/project-infinity-x/out/host/linux-x86/bin/ota_from_target_files/__main__.py",
line 46, in _soong_main
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1541, in <module>
  File "ota_from_target_files.py", line 1512, in main
  File "ota_from_target_files.py", line 1114, in GenerateAbOtaPackage
  File "ota_utils.py", line 926, in Generate
  File "ota_utils.py", line 857, in _Run
  File "common.py", line 328, in RunAndCheckOutput
common.ExternalError: Failed to run command '['delta_generator',
'--out_file',
'/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/payload-kw242f78.bin',
'--partition_names', 'dpm:gz:lk:logo:mcupm:md1img:odm:pi_im
g:scp:spmfw:sspm:system_dlkm:tee:tkv', '--new_partitions',
'/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/dpm.img:/home/ashallowperson/android_development/project-infinity-x/out/soo
ng/.temp/target_filespc1v_wju/RADIO/gz.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/lk.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_fi
lespc1v_wju/RADIO/logo.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/mcupm.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/R
ADIO/md1img.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/IMAGES/odm.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/pi_img.
img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/scp.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/spmfw.img:/home/asha
llowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/sspm.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/IMAGES/system_dlkm.img:/home/ashallowpe
rson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/tee.img:/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/RADIO/tkv.img',
'--new_mapfiles', '::::::/home
/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/IMAGES/odm.map:::::/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/IMAGES/system_dlkm.map::',
'--
new_postinstall_config_file',
'/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/META/postinstall_config.txt',
'--dynamic_partition_info_file',
'/home/ashallowperson/android_development/proje
ct-infinity-x/out/soong/.temp/target_filespc1v_wju/META/dynamic_partitions_info.txt',
'--apex_info_file',
'/home/ashallowperson/android_development/project-infinity-x/out/soong/.temp/target_filespc1v_wju/META/apex_info.pb',
'--major_versi
on', '2', '--security_patch_level', '2026-07-01',
'--enable_zucchini=false', '--enable_lz4diff=false',
'--enable_vabc_xor=true', '--max_timestamp', '1786987767',
'--partition_timestamps', 'odm:1786987767,system_dlkm:1786987767']'
(exit co
de -6):

22:59:30 ninja failed with: exit status 1