clear AHardwareBuffer symbols | libtranssion_bodybeauty
FAILED:
out/soong/.intermediates/vendor/tecno/CM6/libtranssion_bodybeauty/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libtranssion_bodybeauty.so.check_elf_file
out/host/linux-x86/bin/check_elf_file --skip-unknown-elf-machine
--soname libtranssion_bodybeauty.so --shared-lib
out/soong/.intermediates/vendor/tecno/CM6/libst_mobile/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libst_mobile.
so --shared-lib
out/soong/.intermediates/system/logging/liblog/liblog/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/liblog.so
--shared-lib
out/soong/.intermediates/frameworks/native/libs/nativewindow/libnativewindow/android_vend
or_arm64_armv8-2a-dotprod_cortex-a76_shared/libnativewindow.so
--shared-lib
out/soong/.intermediates/frameworks/native/opengl/libs/libGLESv3/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libGLESv3.so
--shared-lib out/soong/.inte
rmediates/frameworks/native/opengl/libs/libEGL/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libEGL.so
--shared-lib
out/soong/.intermediates/bionic/libm/libm/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libm.so
--shar
ed-lib
out/soong/.intermediates/bionic/libc/libc/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libc.so
--shared-lib
out/soong/.intermediates/prebuilts/clang/host/linux-x86/libc++/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_
shared/libc++.so --shared-lib
out/soong/.intermediates/bionic/libdl/libdl/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libdl.so
--system-shared-lib libdl.so
--llvm-readobj=prebuilts/clang/host/linux-x86/clang-r563880c/bin/llvm-
readobj
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so &&
touch
out/soong/.intermediates/vendor/tecno/CM6/libtranssion_bodybeauty/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libtranssion_bodybeauty.so.check_
elf_file
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so:
error: Unresolved symbol: AHardwareBuffer_allocate@LIBNATIVEWINDOW
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so:
error: Unresolved symbol: AHardwareBuffer_describe@LIBNATIVEWINDOW
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so:
error: Unresolved symbol: AHardwareBuffer_lockPlanes@LIBNATIVEWINDOW
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so:
error: Unresolved symbol: AHardwareBuffer_release@LIBNATIVEWINDOW
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so:
error: Unresolved symbol: AHardwareBuffer_unlock@LIBNATIVEWINDOW
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
Some dependencies might be changed, thus the symbol(s) above cannot be
resolved.
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
Please re-build the prebuilt file:
"vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so".
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
If this is a new prebuilt file and it is designed to have unresolved
symbols, add one of the following properties:
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
Android.bp: allow_undefined_symbols: true,
vendor/tecno/CM6/proprietary/odm/lib64/libtranssion_bodybeauty.so: note:
Android.mk: LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
16:17:33 ninja failed with: exit status 1

#### failed to build some targets (04:13 (mm:ss)) ####