use libremosaic_wrapper from ODM instead of vendor | unresolved symbol
FAILED:
out/soong/.intermediates/vendor/tecno/CM6/libcameracustom.plugin/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libcameracustom.plugin.so.check_elf_file
out/host/linux-x86/bin/check_elf_file --skip-unknown-elf-machine
--soname libcameracustom.plugin.so --shared-lib
out/soong/.intermediates/system/logging/liblog/liblog/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/liblog.so
--sha
red-lib
out/soong/.intermediates/system/core/libutils/libutils/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libutils.so
--shared-lib
out/soong/.intermediates/system/core/libcutils/libcutils/android_vendor_arm64_armv8-2a-dotprod
_cortex-a76_shared/libcutils.so --shared-lib
out/soong/.intermediates/vendor/tecno/CM6/libmtkcam_stdutils/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libmtkcam_stdutils.so
--shared-lib out/soong/.intermediates/vendor/tecno/CM6
/libremosaiclib/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libremosaiclib.so
--shared-lib
out/soong/.intermediates/vendor/tecno/CM6/libremosaic_wrapper/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libremosaic_wrapp
er.so --shared-lib
out/soong/.intermediates/bionic/libc/libc/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libc.so
--shared-lib
out/soong/.intermediates/bionic/libm/libm/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/li
bm.so --shared-lib
out/soong/.intermediates/prebuilts/clang/host/linux-x86/libc++/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libc++.so
--shared-lib
out/soong/.intermediates/bionic/libdl/libdl/android_vendor_arm64_armv8-2a-dot
prod_cortex-a76_shared/libdl.so --system-shared-lib libdl.so
--llvm-readobj=prebuilts/clang/host/linux-x86/clang-r563880c/bin/llvm-readobj
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so
&& touch out/soong/.interme
diates/vendor/tecno/CM6/libcameracustom.plugin/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/libcameracustom.plugin.so.check_elf_file
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
error: Unresolved symbol: remosaic_process_gain_set
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note:
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note: Some dependencies might be changed, thus the symbol(s) above
cannot be resolved.
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note: Please re-build the prebuilt file:
"vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so".
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note:
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note: If this is a new prebuilt file and it is designed to have
unresolved symbols, add one of the following properties:
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note:   Android.bp: allow_undefined_symbols: true,
vendor/tecno/CM6/proprietary/odm/lib64/mt6789/libcameracustom.plugin.so:
note:   Android.mk: LOCAL_ALLOW_UNDEFINED_SYMBOLS := true
16:33:36 ninja failed with: exit status 1

#### failed to build some targets (23 seconds) ####

switching to odm provided library since it is exporting required symbol.
placing symlink in vendor so other libs can load.

03:12:36 ashallowperson@inscrutable CM6-A16-Dump → find . -type f -name
"*.so" -printf '%P\0' | xargs -0 -P$(nproc) -I{} sh -c 'out=$(readelf
-Ws "{}" 2>/dev/null | grep "remosaic_process_gain_set"); [ -n "$out" ]
&& (echo "$out" | grep -q " UND " && echo "IMPORT|{}" || echo
"EXPORT|{}")' | sort -t'|' -k1,1 -k2,2 | sed 's/|/ -> /'
EXPORT -> odm/lib64/libremosaic_wrapper.so
IMPORT -> odm/lib64/mt6789/libcameracustom.plugin.so
04:37:30 ashallowperson@inscrutable CM6-A16-Dump →