drop android.hardware.cas | deprecated
in a16 it is provided by apex instead of service.

ERROR: files are incompatible:
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/software from
/system/etc/vintf/compatibility_matrix.8.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/default[0-9]* from
/system/etc/vintf/compatibility_matrix.8.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/vendor[0-9]*_software
from /system/etc/vintf/compatibility_matrix.8.xml
android.hardware.cas@1.2::IMediaCasService/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.cas@1.1::IMediaCasService/default from
/system/etc/vintf/compatibility_matrix.7.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/software from
/system/etc/vintf/compatibility_matrix.7.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/default[0-9]* from
/system/etc/vintf/compatibility_matrix.7.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/vendor[0-9]*_software
from /system/etc/vintf/compatibility_matrix.7.xml
android.hardware.cas@1.2::IMediaCasService/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.cas@1.1::IMediaCasService/default from
/system/etc/vintf/compatibility_matrix.6.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/software from
/system/etc/vintf/compatibility_matrix.6.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/default[0-9]* from
/system/etc/vintf/compatibility_matrix.6.xml
android.hardware.media.c2@1.2::IComponentStore/default is deprecated in
compatibility matrix at FCM Version 202504; it should not be served.
because it matches
android.hardware.media.c2@1.0::IComponentStore/vendor[0-9]*_software
from /system/etc/vintf/compatibility_matrix.6.xml
The following instances are in the device manifest but not specified in
framework compatibility matrix:
    android.hardware.cas@1.2::IMediaCasService/default
    android.hardware.media.c2@1.2::IComponentStore/default
Suggested fix:
1. Update deprecated HALs to the latest version.
2. Check for any typos in device manifest or framework compatibility
matrices with FCM version >= 202504.
3. For new platform HALs, add them to any framework compatibility matrix
with FCM version >= 202504 where applicable.
4. For device-specific HALs, add to
DEVICE_FRAMEWORK_COMPATIBILITY_MATRIX_FILE or
DEVICE_PRODUCT_COMPATIBILITY_MATRIX_FILE.
5. For `android.*` HALs that are using unexpected instance names, the
instance names need to be added to the AOSP framework compatibility
matrices. A regex wildcard can be used if the instance names are
proprietary.
: Success